name: gee
channels:
  - conda-forge
dependencies:
  - python >= 3.7
  - earthengine-api
  - geemap
  - scipy
  - matplotlib
  - pandas
  - geopandas
  - jupyterlab
  - voila
  - ipywidgets
  - nodejs
  - ipympl
  - jupyter_contrib_nbextensions
  - rasterio
  - ipyleaflet
  - nodejs
  - pip
  - pip:
    - elevation
    - gdal2tiles
    - seaborn
